// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1E0Kw1QPZFA-ioPFg7hzO4FUbycpd8m8',
    appId: '1:8842383345:web:257b6c23e3335533eb3e50',
    messagingSenderId: '8842383345',
    projectId: 'flutterauth-7deca',
    authDomain: 'flutterauth-7deca.firebaseapp.com',
    storageBucket: 'flutterauth-7deca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Yeac6TRt4PJ_6QWV7tFNVKXlohDCJgI',
    appId: '1:8842383345:android:2da038c88247ecbbeb3e50',
    messagingSenderId: '8842383345',
    projectId: 'flutterauth-7deca',
    storageBucket: 'flutterauth-7deca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCSBLXhtcsyEQnCYjiJ8pF0qPu4N535WQ',
    appId: '1:8842383345:ios:630becffe5ec4257eb3e50',
    messagingSenderId: '8842383345',
    projectId: 'flutterauth-7deca',
    storageBucket: 'flutterauth-7deca.firebasestorage.app',
    androidClientId: '8842383345-gv0dcjq6stth6vgn8msq01p3r97vkorg.apps.googleusercontent.com',
    iosClientId: '8842383345-gbc0aef1mdppnmrc0h7eemek767f6gp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.loomaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCSBLXhtcsyEQnCYjiJ8pF0qPu4N535WQ',
    appId: '1:8842383345:ios:630becffe5ec4257eb3e50',
    messagingSenderId: '8842383345',
    projectId: 'flutterauth-7deca',
    storageBucket: 'flutterauth-7deca.firebasestorage.app',
    androidClientId: '8842383345-gv0dcjq6stth6vgn8msq01p3r97vkorg.apps.googleusercontent.com',
    iosClientId: '8842383345-gbc0aef1mdppnmrc0h7eemek767f6gp2.apps.googleusercontent.com',
    iosBundleId: 'com.example.loomaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1E0Kw1QPZFA-ioPFg7hzO4FUbycpd8m8',
    appId: '1:8842383345:web:a8e54c7d5a097a2aeb3e50',
    messagingSenderId: '8842383345',
    projectId: 'flutterauth-7deca',
    authDomain: 'flutterauth-7deca.firebaseapp.com',
    storageBucket: 'flutterauth-7deca.firebasestorage.app',
  );
}
